apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: k8s-training
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ealen/echo-server
        ports:
          - containerPort: 8080
